### PR TITLE
Allow bitbake 2.0 override syntax

### PR DESCRIPTION
**Pull request by fbezdeka**
- Allow bitbake 2.0 override syntax
- Update org.jetbrains.intellij plugin to recent version
- Optimize build time by disabling the "searchable options" (AFAIK we don't have something like that)

Please test carefully. I did some tests with my bitbake/Isar layers laying around but there might be corner cases that I did not cover so far.

### CODE REVIEW

**Comment by moqmar** [comment]
Thanks for your contribution & sorry that I didn't review this yet - I don't have a project yet that uses the new syntax, I plan to try it out in the next week though.

**Comment by fbezdeka** [comment]
Any updates? Works fine for some time now...

**Comment by DavidAntliff** [comment]
> Any updates? Works fine for some time now...

There are still a few issues with the parsing: https://github.com/vitalibo/bitbake-intellij-plugin/issues/5#issuecomment-1583500294

**Comment by fbezdeka** [comment]
Well, this issue/MR stalled over one year now. I'm not very optimistic that we will see progress soon...

**Comment by fbezdeka** [comment]
Updated the MR with the results of my one day holiday hacking. I tried to address some issues from #5. Feedback welcome.

**Comment by DavidAntliff** [comment]
@fbezdeka sounds great, but my apologies, I forget, how do I test this again? Is there a build somewhere?

**Comment by fbezdeka** [comment]
Hm... Seems you have to build it on your own. On the long run we might implement something based on github actions that will automatically build pull requests. I will try that now, but not sure if that will work within a few tries.

**Comment by fbezdeka** [comment]
The plugin with this changes applied can be downloaded from github actions now. (See last git commit in this PR).

https://github.com/fbezdeka/bitbake-intellij-plugin/actions/runs/10178590486/artifacts/1759583652

**Comment by fbezdeka** [comment]
Link to the latest build download: https://github.com/fbezdeka/bitbake-intellij-plugin/actions/runs/10202860522/artifacts/1765892776

**Comment by fbezdeka** [comment]
Hm... Up to now I thought that the only valid export statement is `export VAR="value"`, so whitespaces only allowed between `export` keyword and `VAR`. According to some screenshots in #5 whitespaces are allowed everywhere. If so, the solution for the export statements is kind of over engineered and wrong...

Will look into that again soon.

**Comment by fbezdeka** [comment]
Latest build result: https://github.com/fbezdeka/bitbake-intellij-plugin/actions/runs/10213925452/artifacts/1768710293

Everything related to `export` and `EXPORT_FUNCTION` should be fixed now.

**Comment by fbezdeka** [comment]
Latest build result: https://github.com/fbezdeka/bitbake-intellij-plugin/actions/runs/10215397756/artifacts/1769075428

With that, all issues reported in #5 should be fixed now.

Feedback welcome, I'm not planning to address anything on top again. Everything else should be part of a different pull request.

@vitalibo can you have a look / review this pull request once we got positive feedback from @DavidAntliff ?

**Comment by fbezdeka** [comment]
Latest build result: https://github.com/fbezdeka/bitbake-intellij-plugin/actions/runs/10247071178/artifacts/1775814440

- Proper parsing of flags (VAR[flag] = "value" syntax)
- Do no longer allow whitespaces at the beginning of lines, plugin allowed that but bitbake failed to parse
- Reworked addtask,deltask and addhandler statements
- Do no longer allow functions with the opening bracket at the beginning of the next/first line, plugin allowed that but bitbake failed to parse
- Fixed highlighting of python functions at the end of files
- EXPORT_FUNCTIONS should be fine now
- export statements allow all bitbake operators now

**Review by DuckSupremacist — APPROVED** [review]

**Comment by fbezdeka** [comment]
@vitalibo could you please have a look and merge? I think it's wrong when I merge it myself. In addition I can't do the upload to the Jetbrains/IDEA "plugin store".

**Comment by vitalibo** [comment]
Hi @fbezdeka, thanks for your contribution. I am no longer working with Bitbake. Please reach out to @moqmar for further help to upload the plugin to JetBrains/IDEA store. Thanks!

**Review by vitalibo — APPROVED** [review]

**Comment by moqmar** [comment]
Sorry for the delay, thank you Vitalibo for merging. I'm still here (albeit with quite limited time), and have tried it out as well now, created a release & uploaded it to the marketplace. Thanks again for the PR!

**Comment by fbezdeka** [comment]
@moqmar ,first of all: Thanks!

But: Are you sure the upload to the marketplace went as it should? It shows version 1.3, yes, but from 2022. Version missmatch?

**Comment by moqmar** [comment]
Oh, you are right - seems like we are at 1.4 now, but 1.3 was never tagged in git. Fixed that & re-uploaded it; it is now being reviewed.

**Pull request merged**
